# Site settings
title: nonjene
email: reanfn89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  something.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: pasimops
github_username:  nonjene

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

#more_vert:
#  option1:
#    name: Cool Option 1
#    link: www.myawesomelink.com

disqus: false
disqus_shortname: 'nonjene'

# Build settings
markdown: kramdown